name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Updates every night
  workflow_dispatch: # Allows manual update
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: amit265
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_followup: yes
          plugin_lines: yes
